### PR TITLE
Fixed Per-line-item action in Spree not taking quantity into account

### PR DESCRIPTION
**Pull request by ibagmet**

### CODE REVIEW

**Comment by ericsaupe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tGee00cK&#x2F;4149-0-5-spree-sale-pricing-is-not-using-the-lowest-available-sale-price"> (0.5) Spree Sale Pricing is not using the lowest available sale price</a>

**Comment by ericsaupe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tGee00cK&#x2F;4149-0-5-spree-sale-pricing-is-not-using-the-lowest-available-sale-price"> (0.5) Spree Sale Pricing is not using the lowest available sale price</a>

**Comment by xunker** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;asJGPHDS&#x2F;4127-3-per-line-item-action-in-spree-not-taking-quantity-into-account-l"> (3) Per-line-item action in Spree not taking quantity into account {L}</a>

**Comment by n00b2pr0** [comment]
PR for 2.3: https://github.com/deseretbook/spree_sale_pricing/pull/25

**Comment by xunker** [comment]
@n00b2pr0 Should we merge this _and_ #25, or merge this one only and ignore #25? It looks like #25 also includes the same changes (app/models/spree/calculator/percent_on_line_item_msrp.rb) that are in this.

**Comment by n00b2pr0** [comment]
Historically we've been bad at keeping master up to date only merging to `2-3-stable`, but we did create 2 PR's one for each branch. I'm fine with whatever but we use `2-3-stable` in the nibley gemfile.

**Pull request closed without merging**
