### PR TITLE
Add sale pricing to detailed spotlight

### PR DESCRIPTION
**Pull request by n00b2pr0**

### CODE REVIEW

**Comment by n00b2pr0** [comment]
Prior to merging, need to bump version and update Gemfile in https://github.com/deseretbook/nibley/pull/1006

**Comment by n00b2pr0** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jMIiHFFU&#x2F;4066-2-update-promo-banner"> (2) Update Promo Banner</a>

**Comment by n00b2pr0** [comment]
@ericsaupe will you code review this?

**Comment by ericsaupe** [comment]
Looks good :panda_face:

**Pull request merged**
